<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
    }

    /**
     * Reverse the migrations.
     *
     * @param string $foo
     * @return void
     */
    public function down(): void
    {
    }
};
-----
<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     *
     * @return void
     */
    public function up(): void
    {
    }

    /**
     *
     * @param string $foo
     * @return void
     */
    public function down(): void
    {
    }
};
